import mongoose, { Schema, Document, Model } from 'mongoose';

/**
 * Payslip — one document per employee per pay period.
 * Generated by an admin/manager for a given month+year.
 */
export interface IPayslip extends Document {
  ssoUserId: string;
  /** Pay period: e.g. "2025-05" (YYYY-MM) */
  payPeriod: string;
  /** Month number 1-12 */
  month: number;
  /** 4-digit year */
  year: number;

  // ── Earnings ───────────────────────────────────────────────────────────────
  basicSalary: number;
  allowances: number;
  /** Bonus / performance pay added at payroll run time */
  bonus: number;
  /** Total working days in the month */
  workingDays: number;
  /** Days the employee actually worked (present) */
  daysWorked: number;
  /** Gross = (basicSalary + allowances) * (daysWorked / workingDays) + bonus */
  grossSalary: number;

  // ── Deductions ─────────────────────────────────────────────────────────────
  pfDeduction: number;
  professionalTax: number;
  otherDeductions: number;
  totalDeductions: number;

  // ── Net Pay ────────────────────────────────────────────────────────────────
  netSalary: number;

  // ── Meta ───────────────────────────────────────────────────────────────────
  status: 'draft' | 'approved' | 'paid';
  generatedBy: string;   // ssoUserId of admin who ran payroll
  paidAt?: Date;
  notes?: string;
}

const PayslipSchema = new Schema<IPayslip>({
  ssoUserId:        { type: String, required: true, index: true },
  payPeriod:        { type: String, required: true },     // "2025-05"
  month:            { type: Number, required: true },
  year:             { type: Number, required: true },

  basicSalary:      { type: Number, required: true },
  allowances:       { type: Number, default: 0 },
  bonus:            { type: Number, default: 0 },
  workingDays:      { type: Number, required: true },
  daysWorked:       { type: Number, required: true },
  grossSalary:      { type: Number, required: true },

  pfDeduction:      { type: Number, default: 0 },
  professionalTax:  { type: Number, default: 0 },
  otherDeductions:  { type: Number, default: 0 },
  totalDeductions:  { type: Number, default: 0 },
  netSalary:        { type: Number, required: true },

  status:           { type: String, enum: ['draft', 'approved', 'paid'], default: 'draft' },
  generatedBy:      { type: String, required: true },
  paidAt:           { type: Date },
  notes:            { type: String },
}, { timestamps: true });

// Unique constraint: one payslip per user per pay period
PayslipSchema.index({ ssoUserId: 1, payPeriod: 1 }, { unique: true });

export const Payslip: Model<IPayslip> =
  mongoose.models.Payslip ||
  mongoose.model<IPayslip>('Payslip', PayslipSchema);
